config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :itineraries do
    resources :activities, only: [:create, :index]
  end
  resources :activities, except: [:create, :index]
end

app/models/activity.rb
require "open-uri"

class Activity < ApplicationRecord
  belongs_to :itinerary
  validates :datetime, :longitude, :latitude, :title, :category, presence: true
  has_one_attached :photo

  # after_save if: -> { saved_change_to_title? } do
  #   set_photo
  # end

  # geocoding
  geocoded_by :address
  after_validation :geocode, if:
   :will_save_change_to_address?

  private

  def set_photo
    client = OpenAI::Client.new
    response = client.images.generate(parameters: {
      prompt: "Give me an accurate image of  #{title} located at #{address}" , size: "256x256"
    })

    image_id = response["data"][0]["id"]
    url = response["data"][0]["url"]
    file =  URI.open(url)

    photo.purge if photo.attached?

    photo.attach(io: file, filename: "#{image_id}#{id}_#{title}.png", content_type: "image/png")
    return photo
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/itinerary.rb
require "open-uri"

class Itinerary < ApplicationRecord
  # after_save if: -> { saved_change_to_name? } do
  #   set_photo
  # end

  belongs_to :user
  has_many :activities, dependent: :destroy
  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }

  has_one_attached :photo

  # def ai_response

  #   if super.blank?
  #     set_content
  #   else
  #     super
  #   end
  # end

  # private

  # def set_content
  #   # API
  #   # client = OpenAI::Client.new
  #   # response = client.chat(parameters: {
  #   #   model: "gpt-3.5-turbo",

  #   #   messages: [{ role: "user", content: "You are a travel agent with 20 years of experience of travelling the world and you love to create perfect itineraries for customers. You will be building the perfect customised itinerary for a customer.  Each activity needs to be real and contain correct accurate data. The information required for each activity is datetime, Title, Duration, description, address, category, country, city, phone number, url, and the complete precise longitude and latitude. The datetime field which will be populated with a date and time.  Please consider the customers preferences below and complete the assembly instructions procedurally: Preferences: Country: #{name}, Cities: #{answer3}, Date range: #{start_date} to #{end_date}, Preferences: #{answer6}, Accessibility requirements: #{answer6}.  Assembly: 1. create 1 day of the itinerary 2. attribute 3 activities to that day as per the customer's preferences 3. add an eatery 3. repeat the above steps until you reach the end of the specified date range.PRINT OUT ALL ACTIVITIES FOR THE WHOLE DATE RANGE. DO NOT STOP UNTIL YOU HAVE GENERATED 3 ACTIVITIES FOR EACH OF THE DAYS IN THE GIVEN DATE RANGE. Only respond with the required itinerary in an array and please do not send any other information."}]

  #   #   #messages: [{ role: "user", content: "You are a travel agent with 20 years of experience of travelling the world and you love to create perfect itineraries for customers. You will be building the perfect customised itinerary for a customer.  Each activity needs to be real and contain correct accurate data. The information required for each activity is Datetime, Title, duration, description, address, category, country, city, phone number, website url, and the complete precise longitude and latitude. The datetime field which will be populated with a date and time.  Please consider the customers Preferences: Country: #{name}, Cities: #{answer3}, Date range: #{start_date} to #{end_date}, Preferences: #{answer6}, Accessibility requirements: #{answer6}.  Also include datetime field which will be populated with a date and time, and allocate 3 activities per day from #{start_date} until #{end_date}. PRINT OUT ALL ACTIVITIES FOR THE WHOLE DATE RANGE. DO NOT STOP UNTIL YOU HAVE GENERATED 3 ACTIVITIES FOR EACH OF THE DAYS IN THE GIVEN DATE RANGE. Only respond with the required itinerary in an array and please do not send any other information."}]


  #   #   })
  #   # new_content = response["choices"][0]["message"]["content"]
  #   # update(ai_response: new_content)


  #   return new_content


  # end
  private

  def set_photo
    client = OpenAI::Client.new
    response = client.images.generate(parameters: {
      prompt: "Give me an accurate image of a well known landmark or area or tourist attraction in #{answer1}", size: "256x256"
    })

    image_id = response["data"][0]["id"]
    url = response["data"][0]["url"]
    file =  URI.open(url)

    photo.purge if photo.attached?

    photo.attach(io: file, filename: "#{image_id}#{id}_#{name}.png", content_type: "image/png")
    return photo
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :itineraries, dependent: :destroy
  has_many :activities, through: :itineraries


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController


  def index
    # @itineraries = Itinerary.all
    @username = current_user.first_name

    # @itineraries = Itinerary.find(user_id: current_user.id)
    @itinerary = Itinerary.find(params[:itinerary_id])


    @activities_by_datetime = @itinerary.activities.order(datetime: :asc).group_by { |activity| activity.datetime.to_date }.values


    # @activities_by_datetime = @itinerary.activities.order(datetime: :asc)

    # geocoding
    @activities = @itinerary.activities
    # The `geocoded` scope filters only flats with coordinates
    @markers = @activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window_html: render_to_string(partial: "shared/info_window", locals: {activity: activity}),
        marker_html: render_to_string(partial: "shared/marker", locals: {activity: activity})
      }
    end

  end


  def show
    # @itineraries = Itinerary.all
    @username = current_user.first_name
    # @itinerary = Itinerary.find(params[:itinerary_id])


    @activity = Activity.find(params[:id])
    @itinerary = Itinerary.find(@activity.itinerary_id)

    # geocoding
    # @activities = Activity.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = [{
        lat: @activity.latitude,
        lng: @activity.longitude,
        info_window_html: render_to_string(partial: "shared/info_window", locals: {activity: @activity}),
        marker_html: render_to_string(partial: "shared/marker", locals: {activity: @activity})
      }]
  end


  # private

  # def activity_params
  #   params.require(:activity).permit(:country)
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    redirect_to itineraries_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/itineraries/_form.html.erb
<!-- app/views/restaurants/_form.html.erb -->
<%# <script>
  var typed = new Typed('#typed', {
    stringsElement: '#typed-strings'
  });
</script>

<div id="typed-strings">
  <p>Typed.js is a <strong>JavaScript</strong> library.</p>
  <p>It <em>types</em> out sentences.</p>
</div>
<span id="typed"></span> %>


<div data-controller="questions ">



  <%= simple_form_for(@itinerary, html: { class: 'mb-5', data: { 'questions-target': 'form', action: 'turbo:submit-start->questions#startSpinning' } }) do |f| %>
    <p></p>
    <div>

      <span data-questions-target="question" data-strings="<%= ["Which country will you be travelling to?"] %>">

      </span>
        <%= f.input :answer1, label: false, input_html: { class: 'text-answer-box', data: { action: 'keydown.enter->questions#next' }} %>

    </div>

    <div>
      <span data-questions-target="question" data-strings="<%= ["Awesome! Ok when will you start your trip?"] %>">
      </span>
      <%= f.input :start_date, as: :string, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { class: 'text-answer-box', data: { action: 'input->questions#next', controller: "datepicker" } } %>
      <%# <%= f.input :start_date, as: :string,  label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { data: { action: 'keydown.enter->questions#next' } }, input_html: { data: { controller: "datepicker" } } %>
      <%# <%= f.input :custom_field, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { data: { action: 'focusout->questions#next', controller: "datepicker" } } %>
    </div>

    <div>
      <span data-questions-target="question" data-strings="<%= ["and when do you plan to come back?"] %>">
      </span>
      <%= f.input :end_date, as: :string, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { class: 'text-answer-box', data: { action: 'input->questions#next' , controller: "datepicker" }  } %>
    </div>

    <div>
      <span data-questions-target="question" data-strings="<%= ["Nice!  Ok what city/cities! do you want to visit?"] %>">
        <%# <p>What cities do you want to visit?</p> %>
      </span>
      <%= f.input :answer3, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { class: 'text-answer-box', data: { action: 'keydown.enter->questions#next' } } %>
    </div>

    <div>
      <span data-questions-target="question" data-strings="<%= ["Sounds good!  What type of things do you want to do out there?"] %>">
        <%# <p>What type of activities do you like to do?  E.g. sightseeing, nightclubs, beaches etc</p> %>
      </span>
      <%= f.input :answer4, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { class: 'text-answer-box', data: { action: 'keydown.enter->questions#next' } }  %>
    </div>

    <div>
      <span data-questions-target="question" data-strings="<%= ["Ok got it.  What type of cuisine do you like?  Any dietary requirements?"] %>">
        <%# <p>What type of cuisine preferences do you have?  Are there any dietary preferences/requirements to consider?</p> %>
      </span>
      <%= f.input :answer5, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: { class: 'text-answer-box', data: { action: 'keydown.enter->questions#next' } } %>
    </div>

    <div>
      <span data-questions-target="question" data-strings="<%= ["Ok nice.  Lastly, do you or anyone in your group have any accessibility requirements?"] %>">
        <%# <p>Do you or anyone in your travelling group have any accessibility requirements?</p> %>
      </span>
      <%= f.input :answer6, label: false, wrapper_html: { class: 'd-none input-wrapper' }, input_html: {  class: 'text-answer-box', data: { action: 'keydown.enter->questions#next' } }  %>
    </div>

    <%= f.submit "CREATE ITINERARY", class: "btn-register border-3 rounded-3 col-12 mb-4 d-none", data: { 'questions-target': 'button' } %>
  <% end %>

  <div class="spinner d-flex align-items-center justify-content-center d-none" data-questions-target='spinner'>
    <%# <img src="https://lottie.host/5fb6f961-1ef6-4a14-a78d-43a462f9fe89/4sytIe9dGv.json"> %>
    <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
    <dotlottie-player src="https://lottie.host/5fb6f961-1ef6-4a14-a78d-43a462f9fe89/4sytIe9dGv.json" background="transparent" speed="1" style="width: 300px; height: 300px;" loop autoplay></dotlottie-player>
  </div>

</div>

app/views/itineraries/_memory_reel.html.erb
<div class="memory-container"<%#fade-out"%>  >

 <div class="mem-reel-title flex align-items-center justify-content-center">
  <h2 class="text-center"><%=@username%>'s trip to Thailand</h2>
 </div>

  <div id="carouselExample" class="carousel slide mx-3 mb-4 mt-3" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "https://seoimgak.mmtcdn.com/blog/sites/default/files/images/Best%20beaches%20of%20Thailand%20are%20in%20Krabi.jpg", class:"c-img d-block w-100"%>
      </div>

      <div class="carousel-item">
        <%= image_tag "https://assets.traveltriangle.com/blog/wp-content/uploads/2018/08/Khao-Luang-Cave.jpg?tr=w-400", class:"c-img d-block w-100" %>
      </div>

      <div class="carousel-item">
        <%= image_tag "https://www.planetware.com/wpimages/2019/08/thailand-best-places-to-visit-chiang-mai.jpg", class:"c-img d-block w-100"%>
      </div>

      <div class="carousel-item ">
        <%= image_tag "https://media.istockphoto.com/id/1310944330/photo/asia-safari-elephant-family-wildlife-walking-through-the-meadow-in-the-morning.jpg?s=612x612&w=0&k=20&c=VRXpGIajbGV_k6cqqIOweyS6x_LAwE4UQlUhBdz9ums=", class:"c-img d-block w-100"%>
      </div>

      <div class="carousel-item">
        <%= image_tag "https://media.istockphoto.com/id/1287411694/photo/chef-cooking-food-at-street-side-restaurant-in-yaowarat-road-bangkok.jpg?s=612x612&w=0&k=20&c=lu3wmk3q2Dtr1eeKzZcWORI1bW-mGri4bJtH8Sl3MKU=", class:"c-img d-block w-100"%>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="print-icon">
    <a href="https://www.cewe.co.uk/photo-books.html?cref=om_sem_goo_-VT!152344009344!kwd-375607670306!664701601381!!c!g!19610142469_12611_x&s_kwcid=AL!6025!3!664701601381!b!!g!!crew%20photo%20book&keyword=crew%20photo%20book&gad_source=1&gclid=CjwKCAjw9cCyBhBzEiwAJTUWNcwF-L_LHNlUZuY0YrJ1h6rnkCC1ohusA840FrhgQiwQzRm_XYr5WhoCtYUQAvD_BwE" class="btn-tripmate-black share" target="_blank"><i class="fa-solid fa-print"></i></a>
  </div>
</div>

app/views/itineraries/_memory_reel2.html.erb
<div class="memory-container-2 mt-2">
  <div class="mem-reel-title-2 flex align-items-center justify-content-center">
    <h2 class="text-center mt-2"><%=@username%>'s trip to Rome</h2>
  </div>

  <div id="carouselExampleControls" class="carousel slide mx-3 mb-4 mt-3" data-ride="carousel">
    <div class="carousel-inner">

      <div class="carousel-item active">
        <%= image_tag "https://t3.ftcdn.net/jpg/02/27/88/36/360_F_227883696_tvfOO6syjvdRJYZls1FvCSgUqfVAcNXL.jpg", class:"c-img d-block w-100"%>
      </div>

      <div class="carousel-item">
        <%= image_tag "https://www.italyperfect.com/blog/wp-content/uploads/2019/04/Italy-Perfect-Expert-Shares-Rome-Sightseeing-Tips-by-Italy-Perfect4.jpg", class:"c-img d-block w-100" %>
      </div>

      <div class="carousel-item">
        <%= image_tag "https://media.istockphoto.com/id/891284194/photo/pasta-pizza-and-homemade-food-arrangement-in-a-restaurant-rome.jpg?s=612x612&w=0&k=20&c=w9dYWN9kqLixeJcN4OmTP4FCSMY4uh31nrXklBqIngw=", class:"c-img d-block w-100" %>
      </div>

      <div class="carousel-item">
        <%= image_tag "https://www.planetware.com/photos-large/I/pantheon.jpg", class:"c-img d-block w-100" %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="print-icon-2">
    <a href="https://www.cewe.co.uk/photo-books.html?cref=om_sem_goo_-VT!152344009344!kwd-375607670306!664701601381!!c!g!19610142469_12611_x&s_kwcid=AL!6025!3!664701601381!b!!g!!crew%20photo%20book&keyword=crew%20photo%20book&gad_source=1&gclid=CjwKCAjw9cCyBhBzEiwAJTUWNcwF-L_LHNlUZuY0YrJ1h6rnkCC1ohusA840FrhgQiwQzRm_XYr5WhoCtYUQAvD_BwE" class="btn-tripmate-black share" target="_blank"><i class="fa-solid fa-print"></i></a>
  </div>
</div>

app/views/itineraries/index.html.erb
<script class="no-show-itin" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div id="navbar-itin">
  <%= render "shared/navbar" %>
</div>

<div id="map-act" class="itinerary-map position-absolute" data-controller="itineraries">
  <%= render "activities/map" %>
</div>

<div class="itin-body-container card py-5 align-items-center text-left">
  <div class="row py-lg-5">
    <div class="container-fluid mt-5">
      <h1><%=@username%>'s Trips</h1>
    </div>
  </div>
  <div class="container-fluid">
    <ul class="list-unstyled">
      <% @itineraries.each do |itinerary| %>
        <div class="itin-index-card-container card mt-3">
          <div class="itin-index-card card container-fluid mb-1 d-flex py-3">
            <div class="container-fluid d-flex align-items-center justify-content-center">
              <div class="col-5 d-flex content-align-center justify-content-left text-center ms-2 me-2">
                <img class="itin-index-imgs mt-2 mb-2" src="https://source.unsplash.com/256x256/?<%=itinerary.answer1%>">
              </div>
              <div class="itin-index-card-text col-8 d-flex justify-content-center text-left me-2">
                <li> <h5><%= link_to itinerary.name, itinerary_activities_path(itinerary)%></h5> </li>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
  <div class="memory card mt-5 py-5 mb-5" style="
      position: fixed;
      width: 100%;
      height: 100%;
      top:0;
      left:0;
      display: none;
      background-color: #EFEFEF;">
    <%= render "memory_reel" %>
    <%= render "memory_reel2" %>
    <%# <div class="print-icon-2">
      <a href="https://freesnaps.co.uk/" class="btn-tripmate-black share" target="_blank"><i class="fa-solid fa-print"></i></a>
    </div> %>
  </div>
</div>

<div class="c2a-button-map-itin">
  <i class="d-flex align-items-center justify-content-center fa-solid fa-map-location-dot"></i>
</div>

<div class="c2a-button-add-itin">
  <a class="nav-link" href="/itineraries/new">
    <i class="d-flex align-items-center justify-content-center fa-solid fa-plus"></i>
  </a>
</div>

<div class="c2a-button-view-mem">
  <i class="d-flex align-items-center justify-content-center fa-solid fa-images"></i>
</div>

app/views/itineraries/new.html.erb
<%= render "shared/navbar" %>



  <div class="banner-btm mb-5">
    <img class="banner" src="https://images.unsplash.com/photo-1500835556837-99ac94a94552?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=2400">
    <div class="act-index container title-card card shadow">
      <div class="container ">
       <h1>Hey <%=@username%>!</h1>
       <h1> Lets build your dream holiday! </h1>
      </div>


    </div>
  </div>

  <div class=" m-4 justify-content-center d-flex align-content-end flex-grow">
    <div class="card-body card-body-auto-height ">
      <%= render "form", itinerary: @itinerary%>
    </div>
  </div>
</div>

app/views/itineraries/old_index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<%= render "shared/navbar" %>

<div class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto m-5">
      <h1 class="fw-light"><%=@username%>'s Trips</h1>
      <%# <p class="lead text-body-secondary">Welcome to your profile page. Here you will find all your planned trips with all the customised itineraries.  And keep an eye out for the memories folder too!</p> %>
      <%# perhaps add this as a dismissable tooltip? %>

        <%# <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p> %>
    </div>
  </div>
  <div>
    <ul class="list-unstyled">
      <% @itineraries.each do |itinerary| %>
        <li> <%= link_to itinerary.name, itinerary_activities_path(itinerary)%> </li>
        <div class="itin-index-imgs">
          <%= cl_image_tag itinerary.photo.key, alt: "AI-generated image of the location" if itinerary.photo.attached? %>
        </div>
      <% end %>
    </ul>
  </section>
<%#
  <section>
    <button type="button" class="btn btn-tripmate-black btn-lg px-4 gap-3 mt-2">
      <%= link_to "New itinerary", new_itinerary_path%>
    <%# </button>
  </section>
</section>  %>

  <%# map button %>
  <div class="c2a-button-map-itin">
    <i class="d-flex align-items-center justify-content-center fa-solid fa-map-location-dot"></i>
  </div>

  <%# add itinerary button %>
  <div class="c2a-button-add-itin">
    <%# <h1>+</h1> %>
    <i class="d-flex align-items-center justify-content-center fa-solid fa-plus"></i>
  </div>

    <%# add memory button %>
  <div class="c2a-button-view-mem">
    <%# <h1>+</h1> %>
    <i class="d-flex align-items-center justify-content-center fa-solid fa-images"></i>
  </div>

<div class= "itinerary-map">
  <%= render "activities/map" %>
</div>

<div class= "memory">
  <%= render "memory_reel" %>
</div>

<%#tried with css%>
<%# <script>
  document.addEventListener('DOMContentLoaded', function() {
    const memButton = document.querySelector('.c2a-button-view-mem');
    const memoryContainer = document.querySelector('.memory-container');

    memButton.addEventListener('click', function() {
      memoryContainer.classList.toggle('fade-in');
      // memoryContainer.classList.toggle('fade-out');
    });
</script> %>

  <script class="no-show-itin">
    document.addEventListener('DOMContentLoaded', function() {
    const mapButton = document.querySelector('.c2a-button-map-itin');
    const memButton = document.querySelector('.memory');

    let elementsHidden = false;

    mapButton.addEventListener('click', function() {
      if (elementsHidden) {
        // Fade in all elements
        $('body').children().not('.c2a-button-map-itin, .no-show-itin, #navbar-act, #map-act').fadeIn();
      } else {
        // Fade out all elements except the specified ones
        console.log("hello")
        $('body').children().not('.c2a-button-map-itin, .no-show-itin, #navbar-act, #map-act').fadeOut();
      }
      elementsHidden = !elementsHidden;
    });

//original
    memButton.addEventListener('click', function() {
    if (!elementsHidden) {
      // Fade out all elements except the specified ones
      console.log("hello")
      $('body').children()('.memory').fadeOut();
    } else {
      // Fade in all elements
      $('body').children()('.memory').fadeIn();
    }
    !elementsHidden = elementsHidden;
  });


//   tried changes referring to bootstrap carousel
//   memButton.addEventListener('click', function() {
//   const memory = document.querySelector('.memory');
//   const memoryCarousel = document.querySelector('.memory .carousel');
//   if (elementsHidden) {
//     // Fade in the memory carousel
//     memory.style.display = 'block';
//     $(memory).fadeIn();

//     if (memoryCarousel) {
//       memoryCarousel.classList.add('carousel', 'slide');
//       memoryCarousel.setAttribute('data-ride', 'carousel');
//       $(memoryCarousel).carousel('cycle');
//     }
//   } else {
//     // Fade out the memory carousel
//     $(memory).fadeOut();
//   }
// });

  // Existing functionality for collapse/expand buttons
  const collapseAllButton = document.getElementById('collapseAllButton');
  const expandAllButton = document.getElementById('expandAllButton');

  collapseAllButton.addEventListener('click', function() {
    const collapseElements = document.querySelectorAll('.collapse.show');
    collapseElements.forEach(function(collapseEl) {
      new bootstrap.Collapse(collapseEl);
    });
  });

  expandAllButton.addEventListener('click', function() {
    const collapseElements = document.querySelectorAll('.collapse');
    collapseElements.forEach(function(collapseEl) {
      new bootstrap.Collapse(collapseEl, { toggle: false }).show();
    });
  });
});
</script>

app/views/itineraries/show.html.erb
<%= render "shared/navbar" %>
<%= link_to "View all itineraries", "/itineraries" %>