config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :itineraries do
    resources :activities, only: [:create, :index]
  end
  resources :activities, except: [:create, :index]
end

app/models/activity.rb
require "open-uri"

class Activity < ApplicationRecord
  belongs_to :itinerary
  validates :datetime, :longitude, :latitude, :title, :category, presence: true
  has_one_attached :photo

  # after_save if: -> { saved_change_to_title? } do
  #   set_photo
  # end

  # geocoding
  geocoded_by :address
  after_validation :geocode, if:
   :will_save_change_to_address?

  private

  def set_photo
    client = OpenAI::Client.new
    response = client.images.generate(parameters: {
      prompt: "Give me an accurate image of  #{title} located at #{address}" , size: "256x256"
    })

    image_id = response["data"][0]["id"]
    url = response["data"][0]["url"]
    file =  URI.open(url)

    photo.purge if photo.attached?

    photo.attach(io: file, filename: "#{image_id}#{id}_#{title}.png", content_type: "image/png")
    return photo
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/itinerary.rb
require "open-uri"

class Itinerary < ApplicationRecord
  # after_save if: -> { saved_change_to_name? } do
  #   set_photo
  # end

  belongs_to :user
  has_many :activities, dependent: :destroy
  validates :start_date, :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }

  has_one_attached :photo

  # def ai_response

  #   if super.blank?
  #     set_content
  #   else
  #     super
  #   end
  # end

  # private

  # def set_content
  #   # API
  #   # client = OpenAI::Client.new
  #   # response = client.chat(parameters: {
  #   #   model: "gpt-3.5-turbo",

  #   #   messages: [{ role: "user", content: "You are a travel agent with 20 years of experience of travelling the world and you love to create perfect itineraries for customers. You will be building the perfect customised itinerary for a customer.  Each activity needs to be real and contain correct accurate data. The information required for each activity is datetime, Title, Duration, description, address, category, country, city, phone number, url, and the complete precise longitude and latitude. The datetime field which will be populated with a date and time.  Please consider the customers preferences below and complete the assembly instructions procedurally: Preferences: Country: #{name}, Cities: #{answer3}, Date range: #{start_date} to #{end_date}, Preferences: #{answer6}, Accessibility requirements: #{answer6}.  Assembly: 1. create 1 day of the itinerary 2. attribute 3 activities to that day as per the customer's preferences 3. add an eatery 3. repeat the above steps until you reach the end of the specified date range.PRINT OUT ALL ACTIVITIES FOR THE WHOLE DATE RANGE. DO NOT STOP UNTIL YOU HAVE GENERATED 3 ACTIVITIES FOR EACH OF THE DAYS IN THE GIVEN DATE RANGE. Only respond with the required itinerary in an array and please do not send any other information."}]

  #   #   #messages: [{ role: "user", content: "You are a travel agent with 20 years of experience of travelling the world and you love to create perfect itineraries for customers. You will be building the perfect customised itinerary for a customer.  Each activity needs to be real and contain correct accurate data. The information required for each activity is Datetime, Title, duration, description, address, category, country, city, phone number, website url, and the complete precise longitude and latitude. The datetime field which will be populated with a date and time.  Please consider the customers Preferences: Country: #{name}, Cities: #{answer3}, Date range: #{start_date} to #{end_date}, Preferences: #{answer6}, Accessibility requirements: #{answer6}.  Also include datetime field which will be populated with a date and time, and allocate 3 activities per day from #{start_date} until #{end_date}. PRINT OUT ALL ACTIVITIES FOR THE WHOLE DATE RANGE. DO NOT STOP UNTIL YOU HAVE GENERATED 3 ACTIVITIES FOR EACH OF THE DAYS IN THE GIVEN DATE RANGE. Only respond with the required itinerary in an array and please do not send any other information."}]


  #   #   })
  #   # new_content = response["choices"][0]["message"]["content"]
  #   # update(ai_response: new_content)


  #   return new_content


  # end
  private

  def set_photo
    client = OpenAI::Client.new
    response = client.images.generate(parameters: {
      prompt: "Give me an accurate image of a well known landmark or area or tourist attraction in #{answer1}", size: "256x256"
    })

    image_id = response["data"][0]["id"]
    url = response["data"][0]["url"]
    file =  URI.open(url)

    photo.purge if photo.attached?

    photo.attach(io: file, filename: "#{image_id}#{id}_#{name}.png", content_type: "image/png")
    return photo
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :itineraries, dependent: :destroy
  has_many :activities, through: :itineraries


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController


  def index
    # @itineraries = Itinerary.all
    @username = current_user.first_name

    # @itineraries = Itinerary.find(user_id: current_user.id)
    @itinerary = Itinerary.find(params[:itinerary_id])


    @activities_by_datetime = @itinerary.activities.order(datetime: :asc).group_by { |activity| activity.datetime.to_date }.values


    # @activities_by_datetime = @itinerary.activities.order(datetime: :asc)

    # geocoding
    @activities = @itinerary.activities
    # The `geocoded` scope filters only flats with coordinates
    @markers = @activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window_html: render_to_string(partial: "shared/info_window", locals: {activity: activity}),
        marker_html: render_to_string(partial: "shared/marker", locals: {activity: activity})
      }
    end

  end


  def show
    # @itineraries = Itinerary.all
    @username = current_user.first_name
    # @itinerary = Itinerary.find(params[:itinerary_id])


    @activity = Activity.find(params[:id])
    @itinerary = Itinerary.find(@activity.itinerary_id)

    # geocoding
    # @activities = Activity.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = [{
        lat: @activity.latitude,
        lng: @activity.longitude,
        info_window_html: render_to_string(partial: "shared/info_window", locals: {activity: @activity}),
        marker_html: render_to_string(partial: "shared/marker", locals: {activity: @activity})
      }]
  end


  # private

  # def activity_params
  #   params.require(:activity).permit(:country)
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    redirect_to itineraries_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_map.html.erb
<%# <h1>View your activities</h1> %>

<div id='map'
  data-controller="map"
  style="width: 100%; height: 100%; position: fixed; z-index: -2;"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">

<%# passed activity id to stimulus controller %>
  <%# data-map-activity-id-value="<%= @activity.id %>

</div>

app/views/activities/_marker_show.html.erb
<%= image_tag "https://res.cloudinary.com/dopxbkgda/image/upload/v1716219879/marker_v3wyhb.png", height: 35, width: 25, alt: "marker" %>

app/views/activities/index.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <div id="navbar-act">
    <%= render "shared/navbar" %>
  </div>

  <div id="map-act" data-controller="activities">
    <%= render "map" %>
  </div>

  <div>
    <img class="banner" src="https://images.unsplash.com/photo-1500835556837-99ac94a94552?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=2400">
    <%# <img class=“banner” src=“https://source.unsplash.com/2056x256/?travel“> %>
    <div class="act-index container title-card card shadow">
      <div class="container">
       <h1><%=@username%>'s trip to <%=@itinerary.answer1%></h1>
      </div>
      <div class="title-card-bottom-info-bar flex-row align-items-baseline justify-content-between mt-5">
        <%= @itinerary.start_date.strftime("%b %e") %> -
        <%= @itinerary.end_date.strftime("%b %e, %Y") %>

        <div class="inline-buttons">
          <a href="#" class="btn-tripmate-black-share"><i class="fa-solid fa-arrow-up-from-bracket"></i></a>
          <%= image_tag "https://i.pinimg.com/564x/42/b8/19/42b8199cb687ed9c4483fd585870b2ad.jpg", class:"btn-tripmate-black-share-2" %>
        </div>
      </div>

    </div>
  </div>

  <%# map button %>
  <div class="c2a-button-map">
    <i class="d-flex align-items-center justify-content-center fa-solid fa-map-location-dot"></i>
  </div>

  <%# add activity button (not functional) %>
  <div class="c2a-button-add-act">
    <%# <h1>+</h1> %>
    <i class="d-flex align-items-center justify-content-center fa-solid fa-plus"></i>
  </div>


  <%# collapse group test start %>
  <div class="act-list-container container-fluid mt-5">
    <div class="act-list-container mt-5 mb-5 pb-5">
      <div class="panel-group act-expand-control-container">
        <button class="btn-tripmate-black-collapse" type="button" id="expandAllButton"><i class="fa-solid fa-plus"></i></button>
        <button class="btn-tripmate-black-collapse" type="button" id="collapseAllButton"><i class="fa-solid fa-minus"></i></button>
        <%# loops begin %>
        <% @activities_by_datetime.each_with_index do |datetime_activities, index| %>
          <div class="act-card-body mt-2">
            <div class="act-date-list d-flex align-content-center justify-content-left pt-2" id="heading<%= index %>">
              <h5 class="mb-0">
                <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                  <h2><%= datetime_activities.first.datetime.strftime("%B %e, %Y") %></h3>
                  <%# <span class="chevron"><i class="fa-solid fa-angles-left"></i></span> %>
                </button>
              </h5>
            </div>


            <div id="collapse<%= index %>" class="collapse show" aria-labelledby="heading<%= index %>">
              <div class="act-card-body pb-2">
                <% datetime_activities.each do |activity| %>
                  <%= link_to activity_path(activity), class: "activity-link" do %>
                    <div class="act-list-cards card rounded">
                      <div class="card-body">
                        <div class="row">
                          <div class="act-card-time-bar col-md-2 flex justify-content-center">
                            <p class="card-text">
                              <%= activity.datetime.strftime("%H:%M") %>
                                </p>
                                  </div>
                                  <div class="card-text-container col-8 mb-2">
                                    <p class="card-text"><em><%= activity.category %></em></p>
                                    <h5 class="card-title"><%= activity.title %></h5>
                                    <p class="card-text"><small class="text-body-secondary"><%= activity.city %>, <%= activity.phone_number %></small></p>
                                  </div>
                                  <div class="itin-index-img-container col-4 flex justify-content-right">
                                    <img id="act-img" class="itin-index-img-container" src="https://source.unsplash.com/256x256/?<%= activity.category %>: <%= activity.title %> in <%= activity.country %>">
                                  </div>
                          </div>


                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<%= render "shared/navbar" %>
<div class = "show-container col d-flex justify-content-center">
 <div class="card d-flex justify-content-center mb-3">
  <div class="card-body">
      <h1><%= @activity.title %></h1>

    <h2>Date:</h2> <%= @activity.datetime %>
    <h2>Description:</h2> <%= @activity.description %>
    <h2>Category:</h2> <%= @activity.category %>
    <h2>Address:</h2> <%= @activity.address %>
    <h2>Phone_number:</h2> <%= @activity.phone_number %>
    <h2>Url:</h2> <%= @activity.url %>
    <h2>Longitude:</h2> <%= @activity.longitude %>
    <h2>Latitude:</h2> <%= @activity.latitude %>

    </div>
  </div>
</div>

app/views/activities/show.html.erb
<%= render "shared/navbar" %>
<%#
<% <div class = "show-container col d-flex justify-content-center">
 <div class="card d-flex justify-content-center mb-3">
  <div class="card-body"> %>
<%#
      <h1><%= @activity.title %></h1>
<%#
    <h2>Date:</h2> <%= @activity.datetime
    <% <h2>Description:</h2> <%= @activity.description %>
    <%# <h2>Category:</h2> <%= @activity.category %>
    <%# <h2>Address:</h2> <%= @activity.address %>
    <%# <h2>Phone_number:</h2> <%= @activity.phone_number %>
    <%# <h2>Url:</h2> <a href=<%=@activity.url target="_blank"><%= @activity.url %></a>
    <%# <h2>Longitude:</h2> <%= @activity.longitude %>
    <%# <h2>Latitude:</h2> <%= @activity.latitude

    </div>
  </div>
</div>


<div class="py-5 text-center container"> %>

<%#
<a href="#" class="btn btn-tripmate-black btn-lg px-4 gap-3 mt-2"> <%= link_to 'Back to Full Itinerary', itinerary_activities_path(@itinerary)%></a>

<%#
</div>


 <div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>  %>

<div id='map'
  data-controller="activity-map"
  style="width: 100%; height: 100%; position: fixed; z-index: -2;"
  data-activity-map-markers-value="<%= @markers.to_json %>"
  data-activity-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">

</div>